import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import config from "../lib/config";
import * as CosmosClient from '@azure/cosmos'
import { useState } from 'react';
import axios from 'axios';

const Home: NextPage = (props) => {

  const [url, setUrl] = useState('');

  const [shortUrl, setShortUrl] = useState('')

  const handleClick = async() => {
    const response = await axios({
      method: "POST",
      url: "/api/short",
      data: {
        original_url: url
      }
    })
    setShortUrl(response.data.short_url)
  }
  return (
    <div>
      <Head>
        <title>Url Shortener</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

       <input type="text" value={url} onChange={(e) => setUrl(e.target.value)}/> 
      <button onClick={handleClick}> Submit </button>
    {shortUrl.length !== 0 && <a href={shortUrl}> {shortUrl} </a>}
    </div>
  )
}

export default Home
